stages:
  build_DURA_EUROPOS:
    wdir: ../../.
    cmd:
      - rm -rf dataset/pits/DURA_EUROPOS
      - mkdir -p dataset/pits/DURA_EUROPOS
      - python src/alceo/processing/pits_site_dataset.py
        -s data/sites/DURA_EUROPOS
        -o dataset/pits/DURA_EUROPOS
    deps:
      - src/alceo/processing/pits_site_dataset.py
      - data/sites/DURA_EUROPOS/tiles
      - data/sites/DURA_EUROPOS/change
    outs:
      - dataset/pits/DURA_EUROPOS
  build_ASWAN:
    wdir: ../../.
    cmd:
      - rm -rf dataset/pits/ASWAN
      - mkdir -p dataset/pits/ASWAN
      - python src/alceo/processing/pits_site_dataset.py
        -s data/sites/ASWAN
        -o dataset/pits/ASWAN
    deps:
      - src/alceo/processing/pits_site_dataset.py
      - data/sites/ASWAN/tiles
      - data/sites/ASWAN/change
    outs:
      - dataset/pits/ASWAN
