stages:
  build_DURA_EUROPOS:
    wdir: ../../.
    cmd:
      - mkdir -p dataset/pits/DURA_EUROPOS
      - python src/alceo/processing/pits_site_dataset.py
        -s data/sites/DURA_EUROPOS
        -o dataset/pits/DURA_EUROPOS
    deps:
      - src/alceo/processing/pits_site_dataset.py
      - data/sites/DURA_EUROPOS/tiles
      - data/sites/DURA_EUROPOS/change
    outs:
      - dataset/pits/DURA_EUROPOS
