stages:
  produce_tiles_DURA_EUROPOS:
    cmd: python src/alceo/processing/produce_tiles.py 
      -i data/sites/DURA_EUROPOS/images/DE_19_09_2014/DE_19_09_2014_NN_diffuse.tif
      -i /HDD1/gsech/source/alceo/data/sites/DURA_EUROPOS/images/DE_26_5_2013/DE_26_5_2013_NN_diffuse.tif
      -o data/sites/DURA_EUROPOS/tiles.json -p DURA_EUROPOS_
    deps:
    - data/sites/DURA_EUROPOS/images/DE_19_09_2014/DE_19_09_2014_NN_diffuse.tif
    - data/sites/DURA_EUROPOS/images/DE_26_5_2013/DE_26_5_2013_NN_diffuse.tif
    - src/alceo/processing/produce_tiles.py
    outs:
    - data/sites/DURA_EUROPOS/tiles.json
  tilize_image:
    foreach:
      - site: DURA_EUROPOS
        image: DE_19_09_2014/DE_19_09_2014_NN_diffuse
      - site: DURA_EUROPOS
        image: DE_26_5_2013/DE_26_5_2013_NN_diffuse
    do:
      cmd: python src/alceo/processing/rasterize_tiles.py 
          -t data/sites/${item.site}/tiles.json
          -i data/sites/${item.site}/images/${item.image}.tif 
          -a data/sites/${item.site}/area_of_interest.geojson
          -o data/sites/${item.site}/tiles/${item.image}
      deps:
        - src/alceo/processing/rasterize_tiles.py
        - data/sites/${item.site}/tiles.json
        - data/sites/${item.site}/images/${item.image}.tif
        - data/sites/${item.site}/area_of_interest.geojson