vars:
  - sites:
      - site_name: DURA_EUROPOS
        images: 
        - name: DE_19_09_2014/DE_19_09_2014_NN_diffuse
          site_name: DURA_EUROPOS # VERY BAD!!! NORMALIZATION PROBLEM!!! NEEDS REFACTORING
        - name: DE_26_5_2013/DE_26_5_2013_NN_diffuse
          site_name: DURA_EUROPOS
        tile_prefix: DURA_EUROPOS_
stages:
  produce_tiles:
    foreach: ${sites}
    do:
      cmd: python src/alceo/processing/produce_tiles.py 
        -i data/sites/${item.site_name}/images/${item.images[0].name}.tif
        -p ${item.tile_prefix}
        -a data/sites/${item.site_name}/area_of_interest.geojson
        -o data/sites/${item.site_name}/tiles.json 
      deps:
        - src/alceo/processing/produce_tiles.py
        - data/sites/${item.site_name}/images/${item.images[0].name}.tif
        - data/sites/${item.site_name}/area_of_interest.geojson
      outs:
        - data/sites/${item.site_name}/tiles.json 
  tilize_image:
    foreach:
      - site: DURA_EUROPOS
        image: DE_19_09_2014/DE_19_09_2014_NN_diffuse
      - site: DURA_EUROPOS
        image: DE_26_5_2013/DE_26_5_2013_NN_diffuse
    do:
      cmd: python src/alceo/processing/rasterize_tiles.py 
          -t data/sites/${item.site}/tiles.json
          -i data/sites/${item.site}/images/${item.image}.tif 
          -o data/sites/${item.site}/tiles/${item.image}
      deps:
        - src/alceo/processing/rasterize_tiles.py
        - data/sites/${item.site}/tiles.json
        - data/sites/${item.site}/images/${item.image}.tif
      outs:
        - data/sites/${item.site}/tiles/${item.image}

  change_annotations:
    foreach:
      - change: DE_26_5_2013/DE_19_09_2014
        first:
          date: 26/05/2013
          image_folder: DE_26_5_2013
        second:
          date: 19/09/2014
          image_folder: DE_19_09_2014
        site: DURA_EUROPOS
        crs: "EPSG:32637"
    do:
      cmd: python src/alceo/processing/change_from_annotations.py 
        -i data/sites/${item.site}/annotations/pits.geojson 
        -f ${item.first.date} -s ${item.second.date}
        -o data/sites/${item.site}/change/${item.first.image_folder}/${item.second.image_folder}/vectorial
        --crs ${item.crs}
      deps:
        - src/alceo/processing/change_from_annotations.py
        - data/sites/${item.site}/annotations/pits.geojson
      outs:
        - data/sites/${item.site}/change/${item.first.image_folder}/${item.second.image_folder}/vectorial

  rasterize_change:
    foreach:
      - change: DE_26_5_2013/DE_19_09_2014
        base_image: data/sites/DURA_EUROPOS/images/DE_26_5_2013/DE_26_5_2013_NN_diffuse.tif
        change_kind: pits.appeared
        site: DURA_EUROPOS
      - change: DE_26_5_2013/DE_19_09_2014
        base_image: data/sites/DURA_EUROPOS/images/DE_26_5_2013/DE_26_5_2013_NN_diffuse.tif
        change_kind: pits.disappeared
        site: DURA_EUROPOS
    do:
      cmd: mkdir -p data/sites/${item.site}/change/${item.change}/raster/ & rio rasterize data/sites/${item.site}/change/${item.change}/vectorial/${item.change_kind}.geojson 
        --like ${item.base_image} 
        --output data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}.tif
      deps:
        - data/sites/${item.site}/change/${item.change}/vectorial/${item.change_kind}.geojson
        - ${item.base_image}
      outs:
        - data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}.tif
  tilize_change:
    foreach:
      - change: DE_26_5_2013/DE_19_09_2014
        change_kind: pits.appeared
        site: DURA_EUROPOS
      - change: DE_26_5_2013/DE_19_09_2014
        change_kind: pits.disappeared
        site: DURA_EUROPOS
    do:
      cmd: mkdir -p data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}/tiles & python src/alceo/processing/rasterize_tiles.py 
        -t data/sites/${item.site}/tiles.json
        -i data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}.tif 
        -a data/sites/${item.site}/area_of_interest.geojson
        -o data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}/tiles
      deps:
        - src/alceo/processing/rasterize_tiles.py
        - data/sites/${item.site}/tiles.json
        - data/sites/${item.site}/area_of_interest.geojson
        - data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}.tif
      outs:
        - data/sites/${item.site}/change/${item.change}/raster/${item.change_kind}/tiles