site_name: ALCEO Docs
nav:
  - Home: index.md
  - Data sub-system: data.md
  - Modeling sub-system: modeling.md
  - Code Reference: reference/
plugins:
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  # - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          load_external_modules: true
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/autorefs/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_source: true

theme:
  name: material
  features:
    - navigation.indexes
watch:
  - src