seed_everything: 1234
trainer:
  accelerator: gpu
  precision: 16
  max_time: 00:00:10:00
  logger: 
    class_path: alceo.logger.DVCLiveLogger
    init_args:
      run_name: pits_cd 
      dir: log
  log_every_n_steps: 5
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: validation/appeared/IoU
        save_last: True
        save_top_k: 2
        mode: max
        filename: "epoch={epoch:02d}-IoU={validation/appeared/IoU:.5f}"
        auto_insert_metric_name: False
    - class_path: alceo.callback.pits_prediction_writer.TiffPredictionWriter
      init_args:
        output_dir: inference/debug
model:
  network:
    class_path: alceo.model.SiamUnet_diff
    init_args:
      input_nbr: 4
      label_nbr: 2
  loss_fn:
    class_path: segmentation_models_pytorch.losses.JaccardLoss
    init_args:
      mode: multilabel
data:
  batch_size: 12
  train_paths:
    - dataset/pits/DURA_EUROPOS
    - dataset/pits/ASWAN
  validation_paths:
    - dataset/pits/EBLA
  validation_labels:
    - EBLA
optimizer:
  class_path: torch.optim.Adam
  init_args: 
    lr: 1e-4