stages:
  fit_siam_diff:
    wdir: ../../.
    cmd: python -m alceo fit --config config/siam-diff.yaml
    deps:
      - src
      - dataset/pits/train_ASWAN
      - dataset/pits/train_DURA_EUROPOS
      - dataset/pits/train_EBLA
      - dataset/pits/test_ASWAN
      - dataset/pits/test_DURA_EUROPOS
      - dataset/pits/test_EBLA
      - config/siam-diff.yaml
    params:
      - config/siam-diff.yaml:
        - model
        - optimizer
        - lr_scheduler
        - data
    metrics:
      - logs/siam_diff/metrics.json
    plots:
      - logs/siam_diff/plots
    outs:
      - logs/siam_diff/DvcLiveLogger/run/checkpoints/best_IoU.ckpt